### ISSUE TITLE
v1.3.0 Not Available on deno.land

### ISSUE THREAD

**Issue by nakleiderer** [jakajancar/pgc4d#7]
I'm currently getting a 404 when trying to retrieve v1.3.0 from deno land. However, v1.2.0 is available. Recently, denoland released a new registry with webhook integration. Is this webhook configured properly? Did it fail while notifying Deno of the new tag?

Available: https://deno.land/x/pgc4d@v1.2.0
Not Found: https://deno.land/x/pgc4d@v1.3.0

```
> deno run https://deno.land/x/pgc4d@v1.3.0/src/mod.ts
error: Import 'https://deno.land/x/pgc4d@v1.3.0/src/mod.ts' failed: 404 Not Found
```

**Comment by jakajancar** [comment]
I don't know what's going on there. Tried to publish a dummy 1.3.1, still not appearing. Can you just load from GitHub directly?

```ts
import { connectPg } from 'https://raw.githubusercontent.com/jakajancar/pgc4d/v1.3.0/src/mod.ts'
```

**Comment by lucacasonato** [comment]
https://deno.land/posts/registry2

**Comment by jakajancar** [comment]
@nakleiderer 

Should now be fixed:

```ts
import { connectPg } from 'https://deno.land/x/pgc4d@v1.3.3/src/mod.ts'
```
